version: '3'

services:
  my-cows:
    build: .
    container_name: my-cows
    restart: unless-stopped
    expose:
      - "${PORT}"
    environment:
      - DB_PATH=/app/data/scores.sqlite
    volumes:
      - ./data:/app/data
    networks:
      - jakeys_lab

networks:
  jakeys_lab:
    external: true
