services:
  my-cows:
    build: .
    container_name: my-cows
    restart: unless-stopped
    ports:
      - "8081:5000"
    environment:
      - DB_PATH=/app/data/scores.sqlite
      - PORT=5000
    volumes:
      - ./data:/app/data
    networks:
      - jakeys_lab

networks:
  jakeys_lab:
    external: true
