services:
  my-cows-app:
    build: .
    container_name: my-cows-app
    restart: unless-stopped
    ports:
      - "8081:5000"
    environment:
      - DB_PATH=/app/data/scores.sqlite
    volumes:
      - ./data:/app/data
